version: "3"

services:
  pandoc:
    # build:
    #   context: .
    #   dockerfile: ./docker/Dockerfile.pandoc
    image: ghcr.io/xiupos/md2pdf-pandoc
    user: "${UID}:${GID}"
    volumes:
      - .:/worker
    working_dir: /worker

  latex:
    # build:
    #   context: .
    #   dockerfile: ./docker/Dockerfile.latex
    image: ghcr.io/xiupos/md2pdf-latex
    user: "${UID}:${GID}"
    volumes:
      - .:/worker
    working_dir: /worker

  python:
    # build:
    #   context: .
    #   dockerfile: ./docker/Dockerfile.python
    image: ghcr.io/xiupos/md2pdf-python
    user: "${UID}:${GID}"
    volumes:
      - .:/worker
    working_dir: /worker
