name: Build Report

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    name: Build reports
    runs-on: ubuntu-latest
    # runs-on: self-hosted

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Make all
      run: |
        make all
      working-directory: ./

    - name: Archive reports
      uses: actions/upload-artifact@v2
      with:
        name: Reports
        path: |
          ./output-covered.pdf
          ./output-uncovered.pdf
